version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - nolintlint
    - revive
    - gosec
    - bodyclose
  settings:
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: error-return
        - name: error-strings
        - name: increment-decrement
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - gosec
          - errcheck
      - linters:
          - gosec
        text: "G304" # file inclusion via variable — acceptable in config loading
      - path: "internal/version/"
        linters:
          - revive
        text: "var-naming" # 'version' is a conventional package name for build-time vars

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/tbckr/trident
