version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - nolintlint
    - revive
    - gosec
    - bodyclose

linters-settings:
  goimports:
    local-prefixes: github.com/tbckr/trident
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: increment-decrement
  gosec:
    excludes:
      - G304 # file inclusion via variable — acceptable in config loading

issues:
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - gosec
        - errcheck
