version: 2

before:
  hooks:
    - go run github.com/google/go-licenses/v2@latest save ./... --save_path=.build/third_party_licenses --force --ignore=github.com/tbckr/trident
    - go run ./cmd/docgen/main.go --version={{ .Version }} --output-dir=.build

builds:
  - id: trident
    main: ./cmd/trident
    binary: trident
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/tbckr/trident/internal/cli.version={{ .Version }}
      - -X github.com/tbckr/trident/internal/cli.commit={{ .ShortCommit }}
      - -X github.com/tbckr/trident/internal/cli.date={{ .CommitDate }}

gomod:
  proxy: true

archives:
  - id: default
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: .build/third_party_licenses
        dst: THIRD_PARTY_LICENSES
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: .build/completions/*
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: .build/man/*.1
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: "checksums.txt"

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.cdx.json"
    cmd: syft
    args:
      - scan
      - "${artifact}"
      - "--output"
      - "cyclonedx-json=${document}"

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    artifacts: checksum
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"

changelog:
  sort: asc
  filters:
    exclude: ["^chore", "^docs", "^test"]
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Other
      order: 999

nfpms:
  - id: trident
    package_name: trident
    file_name_template: "{{ .ConventionalFileName }}"
    ids:
      - trident
    vendor: tbckr
    homepage: https://github.com/tbckr/trident
    maintainer: tbckr <https://github.com/tbckr>
    description: |-
      Trident — keyless OSINT reconnaissance tool.
      Fast CLI for DNS, ASN, certificate transparency, ThreatMiner, and PGP lookups.
      No API keys required.
    license: GPL-3.0-only
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      # Man pages (generated by before hook)
      - src: .build/man/*.1
        dst: /usr/share/man/man1/
        file_info:
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .CommitDate }}"
      # Bash completion
      - src: .build/completions/trident.bash
        dst: /etc/bash_completion.d/trident
        file_info:
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .CommitDate }}"
      # Zsh completion
      - src: .build/completions/_trident
        dst: /usr/share/zsh/site-functions/_trident
        file_info:
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .CommitDate }}"
      # Fish completion
      - src: .build/completions/trident.fish
        dst: /usr/share/fish/vendor_completions.d/trident.fish
        file_info:
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .CommitDate }}"
      # License
      - src: LICENSE
        dst: /usr/share/licenses/trident/LICENSE
        file_info:
          owner: root
          group: root
          mode: 0644
          mtime: "{{ .CommitDate }}"


snapshot:
  version_template: "{{ .Tag }}-next"
