package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra/doc"

	"github.com/tbckr/trident/internal/cli"
)

func main() {
	version := flag.String("version", "", "version string embedded in man page Source field")
	outputDir := flag.String("output-dir", "dist", "root output directory")
	flag.Parse()
	if err := run(*version, *outputDir); err != nil {
		fmt.Fprintf(os.Stderr, "docgen: %v\n", err)
		os.Exit(1)
	}
}

func run(version, outputDir string) error {
	manDir := filepath.Join(outputDir, "man")
	completionsDir := filepath.Join(outputDir, "completions")
	for _, d := range []string{manDir, completionsDir} {
		if err := os.MkdirAll(d, 0o750); err != nil {
			return fmt.Errorf("create %s: %w", d, err)
		}
	}

	root := cli.NewRootCmd()
	root.DisableAutoGenTag = true // omit "Auto generated by spf13/cobra" footer

	// Man pages — one .1 file per command/subcommand
	header := &doc.GenManHeader{
		Title:   "TRIDENT",
		Section: "1",
		Source:  fmt.Sprintf("trident %s", version),
		Manual:  "trident Manual",
	}
	if err := doc.GenManTree(root, header, manDir); err != nil {
		return fmt.Errorf("man pages: %w", err)
	}

	// Bash completion
	if err := writeCompletion(completionsDir, "trident.bash", func(f *os.File) error {
		return root.GenBashCompletionV2(f, true)
	}); err != nil {
		return err
	}
	// Zsh completion
	if err := writeCompletion(completionsDir, "_trident", func(f *os.File) error {
		return root.GenZshCompletion(f)
	}); err != nil {
		return err
	}
	// Fish completion
	if err := writeCompletion(completionsDir, "trident.fish", func(f *os.File) error {
		return root.GenFishCompletion(f, true)
	}); err != nil {
		return err
	}

	return nil
}

func writeCompletion(dir, name string, gen func(*os.File) error) error {
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		return fmt.Errorf("create %s: %w", name, err)
	}
	if err := gen(f); err != nil {
		_ = f.Close()
		return fmt.Errorf("generate %s: %w", name, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close %s: %w", name, err)
	}
	return nil
}
