name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What you'd like to see added or changed.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Why this is useful and what problem it solves.
    validations:
      required: true

  - type: textarea
    id: proposed
    attributes:
      label: Proposed behavior
      description: Expected CLI interface, output format, flags, etc.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you've thought about.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other information that might help.
